
[package]
name = "discord_music_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12", features = ["framework", "voice"] }
songbird = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15"
